"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Node={id:string;name:string;en:string;kind:string;description:string;keywords:string[];children?:Node[]};
type Topic=[string,string,string[]];
const topic=(parent:string,[name,en,keywords]:Topic,i:number):Node=>({id:`${parent}-${i}`,name,en,kind:"研究トピック",description:`${name}を中心に、${keywords.join("・")}の関係を解き明かし、材料の設計と応用につなげる研究領域です。`,keywords});
const branch=(id:string,name:string,en:string,kind:string,description:string,keywords:string[],topics:Topic[]):Node=>({id,name,en,kind,description,keywords,children:topics.map((x,i)=>topic(id,x,i))});
const fields:Node[]=[
 {id:"metals",name:"金属材料",en:"Metals & Alloys",kind:"構造材料",description:"結晶構造と組織を制御し、強度・靭性・耐熱性を引き出す材料群。社会基盤から航空宇宙までを支えます。",keywords:["結晶","転位","相変態","合金設計"],children:[
  branch("steel","鉄鋼材料","Ferrous alloys","基幹材料","Fe–C系を中心に、相変態と熱処理で幅広い特性を設計します。",["鋼","相変態"],[["炭素鋼","Carbon steels",["フェライト","パーライト","強度"]],["ステンレス鋼","Stainless steels",["耐食性","Cr","不動態"]],["工具鋼","Tool steels",["硬さ","炭化物","焼入れ"]],["先進高強度鋼","Advanced high-strength steels",["TRIP","TWIP","自動車"]]]),
  branch("nonferrous","非鉄金属","Non-ferrous alloys","軽量・耐熱","Al、Ti、Mg、Cu、Niなど固有の機能をもつ合金群です。",["軽量","耐熱"],[["アルミニウム合金","Aluminum alloys",["時効析出","軽量","輸送"]],["チタン合金","Titanium alloys",["比強度","生体適合","航空"]],["マグネシウム合金","Magnesium alloys",["最軽量","鋳造","防食"]],["ニッケル基超合金","Ni-based superalloys",["クリープ","析出強化","タービン"]]]),
  branch("special-metals","特殊金属","Advanced metals","先端材料","秩序や組成の新しい制御法から特異な性能を引き出します。",["非晶質","多元系"],[["金属ガラス","Metallic glasses",["アモルファス","高強度","軟磁性"]],["高エントロピー合金","High-entropy alloys",["多主元素","相安定性","耐熱"]],["形状記憶合金","Shape-memory alloys",["マルテンサイト","超弾性","NiTi"]],["耐火金属","Refractory metals",["W","Mo","超高温"]]]),
  branch("metallurgy","金属プロセス","Physical metallurgy","組織制御","凝固・加工・熱処理によるマルチスケール組織の設計領域です。",["凝固","塑性加工"],[["凝固・鋳造","Solidification",["核生成","デンドライト","偏析"]],["塑性加工","Metal forming",["圧延","鍛造","集合組織"]],["熱処理","Heat treatment",["焼入れ","焼戻し","析出"]],["粉末冶金","Powder metallurgy",["粉末","焼結","HIP"]]])]},
 {id:"ceramics",name:"セラミックス・ガラス",en:"Ceramics & Glass",kind:"耐熱・機能",description:"無機・非金属材料。硬さと高温安定性から電子・光・エネルギー機能まで展開します。",keywords:["焼結","粒界","耐熱","イオン結合"],children:[
  branch("structural-ceramics","構造用セラミックス","Structural ceramics","構造材料","過酷環境で働く高硬度・耐熱材料です。",["硬度","靭性"],[["酸化物セラミックス","Oxide ceramics",["アルミナ","ジルコニア","耐摩耗"]],["非酸化物セラミックス","Non-oxide ceramics",["SiC","Si₃N₄","耐熱"]],["超高温セラミックス","UHTCs",["ホウ化物","炭化物","極超音速"]],["セラミック基複合材","CMCs",["繊維強化","損傷許容","タービン"]]]),
  branch("electroceramics","電子セラミックス","Electroceramics","電子機能","電場・応力・温度に応答する無機機能材料です。",["誘電","圧電"],[["誘電体","Dielectrics",["BaTiO₃","分極","コンデンサ"]],["圧電・強誘電体","Piezo & ferroelectrics",["圧電","ドメイン","センサー"]],["イオン伝導体","Ion conductors",["固体電解質","欠陥","燃料電池"]],["バリスタ・サーミスタ","Varistors & thermistors",["粒界","非線形抵抗","温度"]]]),
  branch("glass","ガラス・非晶質", "Glasses","非晶質","長距離秩序を持たない無機材料とその機能を扱います。",["シリカ","ガラス転移"],[["酸化物ガラス","Oxide glasses",["シリカ","網目構造","窓材"]],["光学ガラス","Optical glasses",["屈折率","分散","レンズ"]],["光ファイバー","Optical fibers",["全反射","低損失","通信"]],["結晶化ガラス","Glass-ceramics",["核生成","低膨張","耐熱"]]]),
  branch("ceramic-process","セラミックプロセス","Ceramic processing","製造","粉体から緻密体・薄膜・多孔体へ形を与えます。",["粉体","焼結"],[["粉体合成","Powder synthesis",["ゾルゲル","共沈","粒径"]],["成形","Forming",["プレス","スリップキャスト","射出"]],["焼結","Sintering",["緻密化","粒成長","拡散"]],["コーティング・薄膜","Ceramic films",["CVD","PVD","溶射"]]])]},
 {id:"polymers",name:"高分子・ソフトマター",en:"Polymers & Soft Matter",kind:"軽量・柔軟",description:"分子鎖の構造と運動性を利用し、軽さ、成形性、柔軟性を生む材料群です。",keywords:["分子鎖","重合","粘弾性","ガラス転移"],children:[
  branch("thermoplastics","熱可塑性高分子","Thermoplastics","成形材料","加熱で軟化し再成形できる汎用樹脂・エンプラです。",["再成形","結晶化"],[["汎用プラスチック","Commodity plastics",["PE","PP","PVC"]],["エンジニアリングプラスチック","Engineering plastics",["PA","PC","POM"]],["スーパーエンプラ","High-performance polymers",["PEEK","PI","耐熱"]],["生分解性高分子","Biodegradable polymers",["PLA","PHA","分解"]]]),
  branch("thermosets","熱硬化・エラストマー","Thermosets & elastomers","架橋材料","架橋ネットワークで強度や大変形を実現します。",["架橋","ゴム弾性"],[["エポキシ樹脂","Epoxy resins",["硬化","接着","複合材"]],["シリコーン","Silicones",["Si–O","耐熱","柔軟"]],["天然・合成ゴム","Rubbers",["加硫","弾性","タイヤ"]],["熱可塑性エラストマー","TPEs",["ブロック共重合","再成形","柔軟"]]]),
  branch("soft-matter","ソフトマター","Soft matter","柔らかい物質","熱揺らぎと自己組織化が支配する柔らかな物質群です。",["自己組織化","レオロジー"],[["ゲル","Gels",["膨潤","架橋","刺激応答"]],["液晶","Liquid crystals",["配向","相転移","ディスプレイ"]],["コロイド","Colloids",["分散","界面","ブラウン運動"]],["生体高分子","Biopolymers",["タンパク質","DNA","多糖"]]]),
  branch("polymer-process","高分子プロセス","Polymer processing","製造・循環","分子設計から加工、再資源化までを扱います。",["重合","流動"],[["重合反応","Polymerization",["連鎖重合","逐次重合","触媒"]],["押出・射出成形","Extrusion & molding",["流動","金型","配向"]],["繊維・フィルム","Fibers & films",["延伸","紡糸","バリア"]],["ケミカルリサイクル","Chemical recycling",["解重合","モノマー","循環"]]])]},
 {id:"electronic",name:"電子・光・量子材料",en:"Electronic, Photonic & Quantum",kind:"機能材料",description:"電子・スピン・光・量子状態を制御し、情報社会を形づくる材料群です。",keywords:["バンド構造","キャリア","光学","薄膜"],children:[
  branch("semiconductors","半導体","Semiconductors","電子材料","キャリアを制御して演算・発光・電力変換を担います。",["ドーピング","バンドギャップ"],[["シリコン","Silicon",["CMOS","pn接合","ウェハ"]],["化合物半導体","Compound semiconductors",["GaAs","InP","高速"]],["ワイドギャップ半導体","Wide-bandgap",["GaN","SiC","パワー"]],["有機・ペロブスカイト半導体","Emerging semiconductors",["有機半導体","ペロブスカイト","印刷"]]]),
  branch("magnetic","磁性・スピン材料","Magnetic & spin materials","スピン","磁化とスピン輸送を利用する材料領域です。",["磁区","スピン"],[["永久磁石","Permanent magnets",["NdFeB","保磁力","モーター"]],["軟磁性材料","Soft magnets",["透磁率","鉄損","トランス"]],["磁気記録材料","Magnetic recording",["磁気異方性","HDD","MRAM"]],["スピントロニクス","Spintronics",["磁気抵抗","スピン流","量子"]]]),
  branch("photonic","光・フォトニック材料","Photonic materials","光機能","光の発生・伝搬・検出を材料で操ります。",["発光","屈折率"],[["発光材料","Luminescent materials",["LED","蛍光体","量子ドット"]],["レーザー材料","Laser materials",["誘導放出","利得","固体レーザー"]],["フォトニック結晶","Photonic crystals",["周期構造","光バンドギャップ","導波路"]],["メタマテリアル","Metamaterials",["負屈折","人工構造","メタサーフェス"]]]),
  branch("quantum","量子材料","Quantum materials","先端物性","創発的な量子状態と新奇物性を探究します。",["強相関","トポロジー"],[["超伝導体","Superconductors",["クーパー対","臨界温度","量子計算"]],["トポロジカル物質","Topological matter",["エッジ状態","ベリー位相","保護"]],["強相関電子系","Strongly correlated systems",["モット転移","磁性","銅酸化物"]],["二次元材料","2D materials",["グラフェン","TMD","ファンデルワールス"]]])]},
 {id:"composites",name:"複合・ナノ・階層材料",en:"Composite & Hierarchical",kind:"設計材料",description:"異なる材料とスケールを組み合わせ、単体を超える性能を階層的に設計します。",keywords:["界面","強化材","マルチスケール","積層"],children:[
  branch("fiber-composites","繊維強化複合材","Fiber composites","軽量構造","連続・短繊維と母材を組み合わせた高比強度材料です。",["繊維","界面"],[["炭素繊維複合材","CFRP",["炭素繊維","積層","航空"]],["ガラス繊維複合材","GFRP",["ガラス繊維","耐食","風車"]],["天然繊維複合材","Natural-fiber composites",["セルロース","軽量","バイオ"]],["セラミック基複合材","Ceramic-matrix composites",["SiC繊維","耐熱","損傷許容"]]]),
  branch("nanomaterials","ナノ材料","Nanomaterials","ナノスケール","寸法・界面・量子閉じ込めに由来する機能を利用します。",["表面積","量子サイズ"],[["ナノ粒子","Nanoparticles",["粒径","表面","触媒"]],["ナノワイヤ・チューブ","1D nanomaterials",["CNT","ナノワイヤ","輸送"]],["二次元ナノ材料","2D nanomaterials",["グラフェン","MXene","剥離"]],["ナノ多孔体","Nanoporous materials",["MOF","ゼオライト","吸着"]]]),
  branch("architected","構造化材料","Architected materials","メタ構造","形と配置そのものを設計変数にする材料群です。",["セル構造","トポロジー"],[["ラティス材料","Lattice materials",["格子","軽量","3Dプリント"]],["力学メタマテリアル","Mechanical metamaterials",["負ポアソン比","座屈","波動"]],["傾斜機能材料","Functionally graded materials",["組成勾配","熱応力","接合"]],["ハニカム・フォーム","Cellular materials",["発泡体","衝撃吸収","断熱"]]]),
  branch("bioinspired","生体模倣・自己修復","Bio-inspired materials","階層・適応","自然の構造原理や修復機構を材料へ翻訳します。",["階層構造","自己修復"],[["真珠層模倣","Nacre-inspired",["レンガモルタル","靭性","積層"]],["生体接着","Bioadhesion",["ヤモリ","ムール貝","濡れ"]],["自己修復材料","Self-healing materials",["可逆結合","マイクロカプセル","寿命"]],["刺激応答材料","Stimuli-responsive",["光","温度","形状変化"]]])]},
 {id:"bioenergy",name:"バイオ・エネルギー材料",en:"Bio & Energy Materials",kind:"社会課題",description:"生命との界面と、エネルギーの変換・貯蔵を担う学際的な材料領域です。",keywords:["生体適合","電気化学","触媒","持続可能性"],children:[
  branch("biomaterials","生体材料","Biomaterials","医療","生体と接触して診断・治療・再生を支える材料です。",["生体適合","医療"],[["インプラント材料","Implant materials",["チタン","人工関節","骨結合"]],["組織工学材料","Tissue engineering",["足場","細胞","再生"]],["ドラッグデリバリー","Drug delivery",["ナノキャリア","放出制御","標的化"]],["バイオセンサー","Biosensors",["受容体","電極","診断"]]]),
  branch("batteries","蓄電池材料","Battery materials","エネルギー貯蔵","電極・電解質・界面で電気化学エネルギーを蓄えます。",["電極","電解質"],[["リチウムイオン電池","Li-ion batteries",["正極","負極","SEI"]],["全固体電池","Solid-state batteries",["固体電解質","界面抵抗","安全性"]],["ナトリウムイオン電池","Na-ion batteries",["資源","層状酸化物","ハードカーボン"]],["次世代電池","Beyond Li-ion",["Li–S","金属空気","多価イオン"]]]),
  branch("conversion","エネルギー変換","Energy conversion","変換デバイス","光・熱・化学エネルギーを相互変換します。",["変換効率","界面"],[["太陽電池","Photovoltaics",["シリコン","ペロブスカイト","光吸収"]],["燃料電池","Fuel cells",["電解質","電極","水素"]],["熱電材料","Thermoelectrics",["ゼーベック効果","熱伝導","廃熱"]],["水電解","Water electrolysis",["HER","OER","グリーン水素"]]]),
  branch("catalysis","触媒・環境材料","Catalysis & environment","反応・浄化","反応経路と物質循環を制御する材料群です。",["活性点","選択性"],[["不均一触媒","Heterogeneous catalysis",["表面反応","担体","ナノ粒子"]],["光触媒","Photocatalysis",["光励起","TiO₂","分解"]],["CO₂分離・変換","CO₂ capture & conversion",["吸着","電解","炭素循環"]],["水処理材料","Water treatment",["膜分離","吸着材","浄化"]]])]},
 {id:"methods",name:"計測・計算・製造",en:"Methods & Manufacturing",kind:"横断基盤",description:"材料をつくり、観て、予測し、データから発見する全領域共通の基盤です。",keywords:["解析","シミュレーション","データ","製造"],children:[
  branch("characterization","構造・組成解析","Characterization","計測","原子からバルクまでの構造と組成を可視化します。",["回折","顕微鏡"],[["X線・中性子回折","Diffraction",["結晶構造","相同定","散乱"]],["電子顕微鏡","Electron microscopy",["SEM","TEM","原子像"]],["分光分析","Spectroscopy",["XPS","Raman","化学状態"]],["三次元解析","3D characterization",["X線CT","APT","トモグラフィー"]]]),
  branch("mechanics","物性・信頼性評価","Properties & reliability","評価","材料が示す応答と劣化のしくみを測ります。",["力学","耐久性"],[["力学試験","Mechanical testing",["引張","硬さ","破壊靭性"]],["熱・電気・磁気物性","Functional properties",["熱伝導","抵抗率","磁化"]],["疲労・クリープ","Fatigue & creep",["寿命","高温","き裂"]],["腐食・環境劣化","Corrosion",["電気化学","酸化","応力腐食"]]]),
  branch("computation","計算材料科学","Computational materials","予測","物理モデルで原子・組織・部材をつなぎます。",["モデル","シミュレーション"],[["第一原理計算","First-principles",["DFT","電子状態","安定性"]],["分子動力学","Molecular dynamics",["原子運動","ポテンシャル","輸送"]],["フェーズフィールド","Phase-field",["組織発展","界面","相変態"]],["有限要素法","Finite element method",["連続体","応力","マルチフィジックス"]]]),
  branch("informatics","材料情報・先進製造","Informatics & manufacturing","発見・実装","データと新しい造形法で材料開発を加速します。",["AI","積層造形"],[["マテリアルズ・インフォマティクス","Materials informatics",["機械学習","記述子","予測"]],["自動・自律実験","Autonomous labs",["ロボット","ベイズ最適化","閉ループ"]],["積層造形","Additive manufacturing",["3Dプリント","溶融池","造形"]],["デジタルツイン","Digital twins",["プロセス監視","モデル更新","品質"]]])]}
];

const flatten=(nodes:Node[],trail:Node[]=[]):{node:Node;trail:Node[]}[]=>nodes.flatMap(node=>[{node,trail:[...trail,node]},...flatten(node.children??[],[...trail,node])]);
const all=flatten(fields); const total=all.length;
const findTrail=(id:string)=>all.find(x=>x.node.id===id)?.trail??[fields[0]];
const processes=["合成・精製","成形・加工","組織制御","評価・解析","計算・データ","循環・再資源化"];

export default function Home(){
 const [trail,setTrail]=useState<Node[]>([fields[0]]); const [query,setQuery]=useState(""); const [lens,setLens]=useState("材料体系"); const searchRef=useRef<HTMLInputElement>(null);
 const selected=trail[trail.length-1];
 const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return all.filter(({node})=>[node.name,node.en,node.kind,node.description,...node.keywords].join(" ").toLowerCase().includes(q)).slice(0,12)},[query]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus()}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 const choose=(node:Node,depth?:number)=>{setTrail(depth===undefined?findTrail(node.id):[...trail.slice(0,depth),node]);setQuery("")};
 const levels=[fields,...trail.map(n=>n.children??[])].filter(x=>x.length);
 return <main><header className="topbar"><a className="brand" href="#top"><span className="brand-mark">M</span><span>MATERIA <i>ATLAS</i></span></a><nav><a href="#atlas">分野マップ</a><a href="#process">研究の流れ</a><a href="#guide">見かた</a></nav><span className="edition">FIELD GUIDE · 02</span></header>
 <section className="hero" id="top"><div className="hero-kicker"><span>EXPLORE THE MATTER</span><span>原子から社会へ</span></div><h1>材料科学の<br/><em>地図をひらく。</em></h1><p>材料、現象、計測、製造——。<br/>枝をたどり、物質を理解するための全景へ。</p><div className="hero-stats"><div><b>4</b><span>探索レイヤー</span></div><div><b>6</b><span>主要領域</span></div><div><b>{total}</b><span>分野・トピック</span></div></div><div className="orbit o1"/><div className="orbit o2"/><i className="atom a1"/><i className="atom a2"/><i className="atom a3"/></section>
 <section className="atlas" id="atlas"><div className="section-heading"><div><span className="eyebrow">DEEP FIELD MAP · {total} NODES</span><h2>深く、広くたどる</h2></div><p>列を右へ進むほど専門的な領域へ。どの階層からでも別の枝へ移れます。</p></div>
 <div className="toolbar"><div className="lenses">{["材料体系","プロセス","特性","用途"].map(x=><button key={x} className={lens===x?"active":""} onClick={()=>setLens(x)}>{x}</button>)}</div><div className="search-wrap"><label className="search"><span>⌕</span><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="例：超伝導、破壊、3Dプリント" aria-label="材料・概念を検索"/><kbd>⌘ K</kbd></label>{query&&<div className="search-results">{results.length?results.map(({node,trail:t})=><button key={node.id} onClick={()=>choose(node)}><span><b>{node.name}</b><small>{t.map(x=>x.name).join(" / ")}</small></span><i>↗</i></button>):<p>一致するトピックがありません</p>}</div>}</div></div>
 <div className="crumbs"><button onClick={()=>setTrail([fields[0]])}>材料科学</button>{trail.map((n,i)=><span key={n.id}><i>›</i><button onClick={()=>setTrail(trail.slice(0,i+1))}>{n.name}</button></span>)}</div>
 <div className="explorer"><div className="level-columns">{levels.map((nodes,depth)=><section className="level" key={depth}><header><span>LEVEL {String(depth+1).padStart(2,"0")}</span><b>{["主要領域","専門分野","材料・現象","研究テーマ"][depth]??"詳細"}</b></header><div>{nodes.map((n,i)=>{const active=trail[depth]?.id===n.id;return <button key={n.id} className={active?"active":""} onClick={()=>choose(n,depth)}><span className="node-count">{String(i+1).padStart(2,"0")}</span><span><b>{n.name}</b><small>{n.en}</small></span>{n.children?.length?<i>{n.children.length} →</i>:<i>↗</i>}</button>})}</div></section>)}</div>
 <aside className="detail" aria-live="polite"><div className="detail-top"><span>SELECTED · LEVEL {trail.length+1}</span><span>↗</span></div><div className="detail-number">{String(all.findIndex(x=>x.node.id===selected.id)+1).padStart(3,"0")}</div><span className="tag">{selected.kind}</span><h3>{selected.name}</h3><p className="en">{selected.en}</p><p className="description">{selected.description}</p><div className="keywords"><small>KEY CONCEPTS</small>{selected.keywords.map(w=><span key={w}>{w}</span>)}</div>{selected.children?.length?<div className="subfields"><small>NEXT LAYER</small><p>{selected.children.length}のトピックへ展開できます</p></div>:<div className="connection"><small>材料科学の基本関係</small><p>プロセス <i>→</i> 構造 <i>→</i> 特性 <i>→</i> 機能</p></div>}</aside></div></section>
 <section className="process" id="process"><div className="section-heading light"><div><span className="eyebrow">RESEARCH FLOW</span><h2>材料が生まれるまで</h2></div><p>どの領域にも共通する、問いから社会実装までの循環。</p></div><div className="process-grid">{processes.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><small>{["SYNTHESIS","PROCESSING","STRUCTURE","ANALYSIS","INFORMATICS","CIRCULARITY"][i]}</small></div>)}</div></section>
 <section className="guide" id="guide"><span className="eyebrow">HOW TO READ</span><h2>ひとつの材料を、<br/>四つの問いで見る。</h2><div className="questions">{[["何からできている？","組成・化学結合・原子配列"],["どうつくる？","合成・加工・熱処理"],["なぜ働く？","構造・組織・物性"],["どこで使う？","機能・信頼性・循環"]].map((x,i)=><p key={x[0]}><b>0{i+1}</b><span><strong>{x[0]}</strong>{x[1]}</span></p>)}</div></section><footer><span>MATERIA ATLAS</span><p>{total}の分野を横断する、材料科学のフィールドガイド。</p><a href="#top">TOP ↑</a></footer></main>
}
