"use client";

import { useMemo, useState } from "react";

type Node = { id:string; name:string; en:string; kind:string; description:string; keywords:string[]; children?:Node[] };
const leaf = (id:string,name:string,en:string,kind:string,description:string,keywords:string[]):Node => ({id,name,en,kind,description,keywords});
const fields:Node[] = [
  {id:"metals",name:"金属材料",en:"Metals & Alloys",kind:"構造材料",description:"結晶構造と組織を制御し、強度・靭性・耐熱性を引き出す材料群。社会基盤から航空宇宙までを支えます。",keywords:["結晶","転位","相変態","合金設計"],children:[leaf("ferrous","鉄鋼材料","Ferrous alloys","基幹材料","Fe–C系を中心とする材料。熱処理と相変態によって幅広い特性を設計します。",["鋼","マルテンサイト","ステンレス"]),leaf("nonferrous","非鉄金属","Non-ferrous","軽量・機能","Al、Ti、Mg、Cu、Niなど。軽量化、導電、耐熱といった固有の強みを持ちます。",["アルミニウム","チタン","超合金"]),leaf("amorphous","金属ガラス","Metallic glass","先端材料","長距離秩序を持たない金属。高強度や優れた軟磁性などを示します。",["アモルファス","過冷却液体"])]},
  {id:"ceramics",name:"セラミックス",en:"Ceramics & Glass",kind:"耐熱・機能",description:"無機・非金属材料。高温安定性、硬さ、絶縁性から電子・エネルギー用途まで展開します。",keywords:["焼結","粒界","イオン結合","耐熱"],children:[leaf("structural-ceramics","構造用セラミックス","Structural ceramics","構造材料","Al₂O₃、SiC、ZrO₂など。高硬度・耐摩耗・耐熱部材に用いられます。",["アルミナ","炭化ケイ素","ジルコニア"]),leaf("electroceramics","電子セラミックス","Electroceramics","機能材料","誘電・圧電・磁性・イオン伝導など、電気的機能を担う材料群です。",["圧電","誘電体","固体電解質"]),leaf("glass","ガラス","Glasses","非晶質","非晶質の無機材料。光学、封止、ディスプレイ、バイオ用途へ広がります。",["シリカ","光ファイバー","結晶化ガラス"])]},
  {id:"polymers",name:"高分子材料",en:"Polymers & Soft Matter",kind:"軽量・柔軟",description:"分子鎖の構造と運動性を利用する材料。軽さ、成形性、柔軟性に優れます。",keywords:["分子鎖","重合","粘弾性","ガラス転移"],children:[leaf("thermoplastics","熱可塑性樹脂","Thermoplastics","汎用・エンプラ","加熱で軟化し再成形できる高分子。循環利用と高機能化が重要テーマです。",["PE","PET","PEEK"]),leaf("thermosets","熱硬化性樹脂","Thermosets","高強度","架橋構造を形成して硬化する樹脂。接着剤や複合材料の母材になります。",["エポキシ","架橋","硬化反応"]),leaf("elastomers","エラストマー","Elastomers","柔軟材料","大きく可逆変形する高分子。ゴムからソフトロボティクスまでを支えます。",["ゴム弾性","ゲル","誘電エラストマー"])]},
  {id:"semiconductors",name:"電子・光材料",en:"Electronic & Photonic",kind:"機能材料",description:"電子・スピン・光の振る舞いを制御し、情報社会を形づくる材料群です。",keywords:["バンド構造","キャリア","光学","薄膜"],children:[leaf("semiconductor","半導体","Semiconductors","電子材料","Siから化合物半導体まで。キャリア制御により演算・発光・電力変換を担います。",["Si","GaN","ドーピング"]),leaf("magnetic","磁性材料","Magnetic materials","スピン","磁化とスピンを利用する材料。モーター、記録、センサーの中核です。",["強磁性","永久磁石","スピントロニクス"]),leaf("quantum","量子材料","Quantum materials","先端物性","電子相関やトポロジーが生む新奇現象を扱う研究フロンティアです。",["超伝導","トポロジカル","強相関"])]},
  {id:"composites",name:"複合・階層材料",en:"Composites",kind:"設計材料",description:"異なる材料を組み合わせ、単体では得られない性能を階層的に設計します。",keywords:["界面","強化材","マルチスケール","積層"],children:[leaf("frp","繊維強化複合材","Fiber composites","軽量構造","炭素・ガラス繊維と樹脂を組み合わせ、比強度を高めた材料です。",["CFRP","積層板","界面破壊"]),leaf("nano","ナノ複合材料","Nanocomposites","機能・強化","ナノ粒子や2次元材料を分散させ、力学・電気・バリア特性を変えます。",["ナノ粒子","グラフェン","分散"]),leaf("biomimetic","生体模倣材料","Bio-inspired","階層構造","骨、貝殻、植物などの構造原理を人工材料の設計へ翻訳します。",["傾斜構造","自己修復","接着"])]},
  {id:"bioenergy",name:"バイオ・エネルギー材料",en:"Bio & Energy",kind:"社会課題",description:"生命との界面や、エネルギーの変換・貯蔵を担う学際的な材料領域です。",keywords:["生体適合","電気化学","触媒","持続可能性"],children:[leaf("biomaterials","生体材料","Biomaterials","医療","生体と接触して働く材料。インプラント、再生医療、薬物送達に関わります。",["生体適合性","組織工学","DDS"]),leaf("battery","蓄電池材料","Battery materials","エネルギー貯蔵","電極・電解質・界面を設計し、安全性とエネルギー密度を高めます。",["リチウムイオン","全固体","界面反応"]),leaf("catalyst","触媒・変換材料","Catalysis & conversion","エネルギー変換","反応経路を制御し、水素、燃料電池、CO₂変換などを可能にします。",["電極触媒","光触媒","水素"])]}
];
const processes=["合成・精製","成形・加工","組織制御","評価・解析","計算・データ","循環・再資源化"];
export default function Home(){
 const [selected,setSelected]=useState<Node>(fields[0]); const [query,setQuery]=useState(""); const [lens,setLens]=useState("材料体系");
 const visible=useMemo(()=>{const q=query.trim().toLowerCase(); if(!q)return fields; return fields.map(f=>({...f,children:f.children?.filter(n=>[n.name,n.en,n.kind,n.description,...n.keywords].join(" ").toLowerCase().includes(q))})).filter(f=>[f.name,f.en,f.kind,f.description,...f.keywords].join(" ").toLowerCase().includes(q)||(f.children?.length??0)>0)},[query]);
 return <main><header className="topbar"><a className="brand" href="#top"><span className="brand-mark">M</span><span>MATERIA <i>ATLAS</i></span></a><nav><a href="#atlas">分野マップ</a><a href="#process">研究の流れ</a><a href="#guide">見かた</a></nav><span className="edition">FIELD GUIDE · 01</span></header>
 <section className="hero" id="top"><div className="hero-kicker"><span>EXPLORE THE MATTER</span><span>構造から社会へ</span></div><h1>材料科学の<br/><em>地図をひらく。</em></h1><p>金属、セラミックス、高分子、半導体——。<br/>物質を理解し、つくり、機能へ変える学問の全景。</p><div className="hero-stats"><div><b>6</b><span>主要領域</span></div><div><b>18</b><span>研究分野</span></div><div><b>∞</b><span>つながり</span></div></div><div className="orbit o1"/><div className="orbit o2"/><i className="atom a1"/><i className="atom a2"/><i className="atom a3"/></section>
 <section className="atlas" id="atlas"><div className="section-heading"><div><span className="eyebrow">FIELD MAP</span><h2>分野をたどる</h2></div><p>枝を選ぶと、その領域の輪郭と重要な概念が見えてきます。</p></div><div className="toolbar"><div className="lenses">{["材料体系","プロセス","特性","用途"].map(x=><button key={x} className={lens===x?"active":""} onClick={()=>setLens(x)}>{x}</button>)}</div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="材料・概念を検索" aria-label="材料・概念を検索"/><kbd>⌘ K</kbd></label></div>
 <div className="map-layout"><div className="tree"><div className="root-node"><small>ROOT</small><b>材料科学</b><span>Materials Science</span></div><div className="trunk"/><div className="branches">{visible.length?visible.map((f,i)=><div className="branch" key={f.id}><button className={`parent-node ${selected.id===f.id?"selected":""}`} onClick={()=>setSelected(f)}><span className="node-index">0{i+1}</span><span><b>{f.name}</b><small>{f.en}</small></span><span>＋</span></button><div className="children">{f.children?.map(n=><button key={n.id} className={selected.id===n.id?"selected":""} onClick={()=>setSelected(n)}><span>{n.name}</span><small>{n.en}</small></button>)}</div></div>):<div className="empty">一致する分野がありません。</div>}</div></div>
 <aside className="detail" aria-live="polite"><div className="detail-top"><span>SELECTED FIELD</span><span>↗</span></div><div className="detail-number">{String(fields.findIndex(f=>f.id===selected.id||f.children?.some(c=>c.id===selected.id))+1).padStart(2,"0")}</div><span className="tag">{selected.kind}</span><h3>{selected.name}</h3><p className="en">{selected.en}</p><p className="description">{selected.description}</p><div className="keywords"><small>KEY CONCEPTS</small>{selected.keywords.map(w=><span key={w}>{w}</span>)}</div><div className="connection"><small>材料科学の基本関係</small><p>プロセス <i>→</i> 構造 <i>→</i> 特性 <i>→</i> 機能</p></div></aside></div></section>
 <section className="process" id="process"><div className="section-heading light"><div><span className="eyebrow">RESEARCH FLOW</span><h2>材料が生まれるまで</h2></div><p>どの領域にも共通する、問いから社会実装までの循環。</p></div><div className="process-grid">{processes.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><small>{["SYNTHESIS","PROCESSING","STRUCTURE","ANALYSIS","INFORMATICS","CIRCULARITY"][i]}</small></div>)}</div></section>
 <section className="guide" id="guide"><span className="eyebrow">HOW TO READ</span><h2>ひとつの材料を、<br/>四つの問いで見る。</h2><div className="questions">{[["何からできている？","組成・化学結合・原子配列"],["どうつくる？","合成・加工・熱処理"],["なぜ働く？","構造・組織・物性"],["どこで使う？","機能・信頼性・循環"]].map((x,i)=><p key={x[0]}><b>0{i+1}</b><span><strong>{x[0]}</strong>{x[1]}</span></p>)}</div></section><footer><span>MATERIA ATLAS</span><p>材料を知ることは、未来のつくり方を知ること。</p><a href="#top">TOP ↑</a></footer></main>
}
